DROP TABLE IF EXISTS aquarist;
DROP TABLE IF EXISTS tank;

CREATE TABLE aquarist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE tank (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  length FLOAT NOT NULL,
  width FLOAT NOT NULL,
  depth FLOAT NOT NULL,
  volume FLOAT NOT NULL,
  FOREIGN KEY (name) REFERENCES aquarist (id)
);
